reviews:
  auto_review:
    enabled: true
    
path_filters:
  include:
    - "src/**/*.java"
    - "pom.xml"
  exclude:
    - "target/**"

rules:
  - security_issues
  - bugs
  - code_quality
  - best_practices
